---
repo-name: peripherals-aws-rds
categories:
  - Cloud
  - DevOps
display-name: Amazon RDS
manufacturer: Amazon
product: RDS
description: Amazon Relational Database Service (Amazon RDS) makes it easy to set up, operate, and scale a relational database in the cloud.
